load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "decco",
    deps = [  "//3rdparty/jvm/com/chuusai:shapeless" ],
    exports = ["//3rdparty/jvm/com/chuusai:shapeless"],
)

scala_test(
    name = "tests",
    deps = [ "decco",
             "//src/io/iohk/codecs/nio/test/utils",
             "//3rdparty/jvm/org/mockito:mockito_core",
             "//3rdparty/jvm/org/scalacheck:scalacheck" ]
)
