load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "utils",
    deps = [ "//src/io/iohk/decco" ],
    external = [
      "org.scalatest:scalatest%",
      "org.scalacheck:scalacheck%",
      "org.mockito:mockito-core",
    ]

)

